### ISSUE TITLE
세로 사진 두장

### ISSUE THREAD

**Issue by PinkWink** [uzugoer/CCZ-CROSS#1]
세로 사진 두장을 나란히 <TABLE class="dual" ... 방법으로 걸면
두장이 잘 배치는 되지만...
마치 가로 크기처럼 잘려서 나타나는 형상이 있어요^^

**Comment by uzugoer** [comment]
네, 의도된 바가 그렇습니다.
dual 과 triple 구조에 사용되는 이미지들은 모두 같은 너비와 같은 높이를 가지게 됩니다. 

원본 이미지 비율대로 출력할 경우 둘쑥날쑥한 이미지들이 배치되기에 이미지를 비율에 맞게 자르게됩니다. 관련하여 [CSS로 유동적인 컨테이너 너비에 기반한 이미지 비율 유지, 가운데 정렬, 자르기](http://webdir.tistory.com/487) 에 포스팅한 내용이 수정에 도움이 될 것입니다. 

몇일 전에 티스토리 새 반응형 스킨 #2가 배포되면서 dual 과 triple 관련된 업데이트가 있었습니다. 관련 사항을 살펴봤을때 구조부터 바뀌고 본문 너비를 넘지않으면서 이미지 원본 비율 그대로를 노출하도록 스타일링이 되어 있었습니다. 아마 원하시는 스타일이 그와 같지 않을까 생각합니다. 다만, 관련 구조변경이 이전에 삽입된 dual, triple 의 호환을 염두에 두지 않고, 새로 생성하는 것들에 한해서만 적용되었기에 하루만에 다시 원점으로 되돌렸더군요.

현재로선, 해당 업데이트가 정상적으로 이루어지는 것을 지켜보고 있습니다.

**Comment by PinkWink** [comment]
그렇군요... 여기.. 저의 얇디얇은 지식이 문제네요...
흠... 매뉴얼을 사실 읽긴했는데.. 그게 이 말을 의미하는지를 몰랐네요~~~
허접 이슈제기에 답변 정말 감사합니다~~~^^
