### ISSUE TITLE
로딩 중 멈춤

### ISSUE THREAD

**Issue by PinkWink** [uzugoer/CCZ-CROSS#2]
어떤 경우인지는 모르지만...
페이지 로딩중  제목... 우측 사이드바, 댓글 부분은 모두 나타나는데...
본문이 로딩되지 않고 비어 있는 경우가 발생합니다.
이럴때는 아무리 기다려도 되지 않고..
새로고침을 누르면 다시 잘 페이지를 로딩하더라구요..

**Comment by uzugoer** [comment]
해당 스킨은 fouc 가 적용되어 있습니다. 
[스킨 제어하기](http://ccz-cross.tistory.com/31) 에 fouc 조정에 관하여 짧은 팁이 있습니다.

또한, _skin.html_ 파일에  <code>.fouc</code> 클래스를 찾아 삭제하시면 관련 효과가 사라집니다.
로딩이 느리게 늦겨진다면 원하시는 부분의 해당 클래스를 삭제하시고 테스트해보세요.

fouc 처리가 된 부분은 페이지가 모두 로딩되어야 본문이 등장합니다. 로딩이 완료되지 않는 경우는 외부에서 삽입되는 스크립트(각종 광고스크립트, 위젯등등)의 오류가 발생한 경우일 확률이 높습니다.

**Comment by PinkWink** [comment]
페이지가 로딩되는 모습이 멋있다고 생각했는데... 가끔 로딩이 안되는 듯 하는 현상으로 고민이었는데...
알려주셔서 감사합니다.
fouc가 정확히 무엇인지 모르는 무식함이 살짝꿍 창피하긴한데.. 아무튼 감사합니다.^^
그리고.. 다시한번...
제가 매뉴얼을 숙지하지 않은 문제군요.ㅠㅠ
